version: '2.2'
services:
    client: 
      stdin_open: true
      build: ./client
      ports:
        - '3000:3000'
      depends_on:
        - api
    api:
      build: ./
      ports:
        - '5000:5000'